[project]
name = "sql_lab"
version = "0.1.0"
description = "sql work for DS2022"
readme = "README.md"
authors = [
    { name = "sirinarne", email = "sirinarne2025@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mysql-connector-python>=26.7.0",
    "pandas>=3.0.6",
]

[project.scripts]
lab-04-sql-siri = "lab_04_sql_siri:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
